config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :skip => [:sign_in]
  ActiveAdmin.routes(self)

  root 'site#index'
  post '/' => 'site#index'
  match 'ribric/:name' => 'site#rubric', :as => 'rubric_filter', via: [:get, :post]
  match 'project/:name' => 'site#project', :as => 'project_filter', via: [:get, :post]
  match 'journal/:number' => 'site#index', :as => 'journal_filter', via: [:get, :post]
  get 'journal/view/:number' => 'site#view_journal', :as => 'journal_view'
  match 'tag/' => 'site#tag', :as => 'tags_filter', via: [:get, :post]
  match 'archive(/:number)' => 'site#archive', :as => 'journal_details', via: [:get, :post]
  match 'article/:alias' => 'site#article', :as => 'article_page', via: [:get, :post]
  match 'adverts(/:categorie(/:subcategorie))' => 'site#ad', :as => 'ad', via: [:get, :post]
  match 'partners' => 'site#partners', via: [:get, :post]
  match 'contacts' => 'site#contacts', via: [:get, :post]
  match 'advertisers' => 'site#advertisers', via: [:get, :post]
  match 'search' => 'site#search', :as => 'search', via: [:get, :post]
  match '/user/:id' => 'site#profile', :as => 'profile', via: [:get, :post]
  get '/ad/export' => 'site#ad_export'
  
  post 'ajax/like' => 'ajax#like'
  post 'ajax/get_subcategories' => 'ajax#get_subcategories'
  post 'ajax/vote' => 'ajax#vote'
  post 'ajax/del_comment' => 'ajax#del_comment'
  
  mount Ckeditor::Engine => '/ckeditor'

end

app/views/layouts/_left_filter.html.erb
<span class="rubric">РУБРИКИ</span>
                <ul class="rubric-menu">
                	<% @rubric = Rubric.all %>
                	<% @rubric.each do |r|%>
                		<% if params[:name] != r.alias %>
                    		<li><%= link_to r.name, rubric_filter_path(r.alias)%></li>
                    	<% else %>
                    		<li class="active"><%= r.name %></li>
                    	<% end %>
                    <% end %>
                    <!--<li class="active">Культура
                        <ul class="sub-rubric">
                            <li><a href="#">Культура</a></li>
                            <li class="active">Культура</li>
                        </ul>
                    </li>-->
                </ul>
                <span class="rubric">СПЕЦПРОЕКТЫ</span>
                <ul class="rubric-menu">
                    <% @specrubric = Specrubric.all %>
                	<% @specrubric.each do |r|%>
                    	<% if params[:name] != r.alias %>
                    		<li><%= link_to r.name, project_filter_path(r.alias)%></li>
                    	<% else %>
                    		<li class="active"><%= r.name %></li>
                    	<% end %>
                    <% end %>
                </ul>

app/views/layouts/_left_panel_ad_list.html.erb
<ul class="filter">
				<% categories = AdCategorie.all %>
				<% categories.each do |c| %>
					<li>
						<%= link_to "#{image_tag(c.icon.url(:thumb), width: 13)} <span>#{c.name}</span>".html_safe, ad_path(c.alias)%>
						<% subcategories = AdSubcategorie.where("ad_categorie_id = ?", c.id)%>
						<% if subcategories != 0 && params['categorie'] == c.alias%>
							<ul class="sub-filter">
							<% subcategories.each do |s| %>
								<li>
									<% if params[:subcategorie] == s.alias%>
										<li class="active"><%= s.name %></li>
									<% else%>
										<%= link_to s.name, ad_path(c.alias, s.alias) %>
									<% end %>
								</li>
							<% end %>
							</ul>
						<% end %>
					</li>
				<% end %>
                <!--<li><a href="#"><img src="im/nedv.png" width="13"/> <span>Недвижимость</span></a></li>
                <li><a href="#"><img src="im/nedv.png" width="13"/> <span>Недвижимость</span></a></li>
                <li><a href="#"><img src="im/nedv.png" width="13"/> <span>Недвижимость</span></a></li>
                <li><a href="#"><img src="im/nedv.png" width="13"/> <span>Недвижимость</span></a></li>
                <li class="active"><img src="im/nedv.png" width="13"/> <span>Недвижимость</span>
                    <ul class="sub-filter">
                        <li><a href="#">Продам</a></li>
                        <li class="active">Куплю</li>
                    </ul>
                </li>-->
            </ul>

app/views/layouts/_right_panel.html.erb
<div class="right-panel">
                <div class="login-form">
                <% if user_signed_in? %>
                	<span class="hello-text">Здравствуйте,</span>
                	<span class="hello-text-name"><%= current_user.name %></span>
                	 <%= link_to 'Кабинет', profile_path(current_user.id), class: 'register-link' %>
                	 <%= link_to "", destroy_user_session_path, method: :delete, class: 'logout-btn' %>
                <% else %>
                    <%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
                        <fieldset>
                            <label><%= f.label :email %>&nbsp;&nbsp;</label>
                            <%= f.text_field :email, autofocus: true %>
                        </fieldset>
                        <fieldset>
                            <label><%= f.label :password %></label>
                            <%= f.password_field :password, autocomplete: "off" %>
                        </fieldset>
                        <%= link_to 'Регистрация', new_user_registration_path, class: 'register-link' %>
                        <%= f.submit "" %>
                    <% end %>
                <% end %>
                </div>
                <% banner = Banner::where('label = "right_panel_banner"')[0]%>
                <% if banner.link != '#'%>
                	<a href="<%= banner.link %>" class="banner">
                <% end %>
                	<img src="<%= banner.image.url(:original) %>" <%= (banner.link == '#') ? 'class=no-link-banner-panel' : ''%>>
                 <% if banner.link != '#'%>
                	</a>
                <% end %>
                <div class="vote">
                    <span>Голосование</span>
                    <span class="vote-header"><%= AddText.find_by_label('vote_header').content%></span>
                    <% if(session[:vote].blank?)%>
                    	<form id="vote_form">
                    		<% votes = Vote.all %>
	                		<% votes.each do |v|%>
	                			<input type="radio" name="vote" value="<%= v.id%>"><span class="vote-label"><%= v.vote_variant%></span><br/>
	                		<% end %>
	                    	<a href="#" id="vote_btn"></a>
	                    </form>
	                <% else %>
	                	<% votes = Vote.all %>
	                	<% votes.each do |v|%>
	                		<span class="vote-label" style="font-size: 16px; margin-top: 10px;"><%= v.vote_variant+' - '+v.vote_value.to_s %></span><br/>
	                	<% end %>
	                <% end %>
                </div>
				<script type="text/javascript" src="//vk.com/js/api/openapi.js?115"></script>
				
				<!-- VK Widget -->
				<div id="vk_groups"></div>
				<script type="text/javascript">
				VK.Widgets.Group("vk_groups", {mode: 0, width: "158", height: "400", color1: 'FFFFFF', color2: '2B587A', color3: '5B7FA6'}, 74562325);
				</script>
            </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <link rel="icon" type="image/png" href="favicon.png">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.11.1/themes/smoothness/jquery-ui.css">
    <script src="//code.jquery.com/ui/1.11.1/jquery-ui.js"></script>
    <title><%= @meta_title.reverse.join("&nbsp;&mdash;&nbsp;").html_safe%></title>
    <%= csrf_meta_tag %>
    <script type="text/javascript">
    $(function() {
    	$( document ).tooltip();
  	});
  </script>
</head>
<body>
	<a href="#" id="ad-btn-right" class="send-btn"></a>
    <div class="header">
        <div class="container-center">
            <div class="header-left">
                <a href="/"><img src="/im/logo.png" alt=""/></a>
            </div>
            <div class="header-right">
                    <ul class="menu">
                        <%= is_current('site', 'index', nil, '/', 'Главная').html_safe%>
                        <%= is_current('site', 'archive', nil, '/archive', 'Архив').html_safe%>
                        <%= is_current('site', 'ad', nil, '/adverts', 'Объявления').html_safe%>
                        <%= is_current('site', 'advertisers', nil, '/advertisers', 'Рекламодателям').html_safe%>
                        <%= is_current('site', 'partners', nil, '/partners', 'Партнеры').html_safe%>
                        <%= is_current('site', 'contacts', nil, '/contacts', 'Контакты').html_safe%>
                        <li class="send-btn">ПОДАТЬ ОБЪЯВЛЕНИЕ</li>
                    </ul>
                    <div class="header-right-bottom">
                        <div class="header-search">
                        	<%= form_tag search_path, method: 'get' do %>
                            	<%= text_field_tag 'q', params[:q], :class => "search-input", :placeholder => 'ПОИСК' %>
                            	<%= submit_tag '', class: "search-btn" %>
                            <% end %>
                        </div>
                        <div class="header-contacts">
                            <%= Contacts.first.address %><br />
                            <%= Contacts.first.build %><br />
                            <a href="https://vk.com/pochem40" style="font-family: Tahoma; color: #525252; font-size: 13px;"><img src="/im/vk.png" width="16" style="position: relative;top: 5px;margin-right: 3px;">https://vk.com/pochem40</a>
                        </div>
                        <div class="header-phone">
                            <img src="/im/phone.png" />
                            <span class="code"><%= Contacts.first.phone_code %></span>
                            <span class="phone-number-header"><%= Contacts.first.phone %></span>
                        </div>
                    </div>
            </div>
        </div>
    </div>
    <div class="main">
        <div class="container-center">
            <div class="left-panel">
            	<% if controller.controller_name == 'site' && controller.action_name == 'ad' && params[:categorie] %>
            		<%= render :partial => 'layouts/left_panel_ad_list' %>
            	<% else %>
                	<%= render :partial => 'layouts/left_filter' %>
                <% end %>
            </div>
            <div class="main-panel">
                <div class="top-offers">
                	<% banner = Banner::where('label = "top_left_banner"')[0]%>
                <% if banner.link != '#'%>
                	<a href="<%= banner.link %>">
                <% end %>
                	<img src="<%= banner.image.url(:original) %>" <%= (banner.link == '#') ? 'class=no-link-banner' : ''%>>
                <% if banner.link != '#'%>
                	</a>
                <% end %>
                
                <% banner = Banner::where('label = "top_center_banner"')[0]%>
                <% if banner.link != '#'%>
                	<a href="<%= banner.link %>">
                <% end %>
                		<img src="<%= banner.image.url(:original) %>" <%= (banner.link == '#') ? 'class=no-link-banner' : ''%>>
               	<% if banner.link != '#'%>
                	</a>
               	<% end %>
               	
                <% banner = Banner::where('label = "top_right_banner"')[0]%>
                <% if banner.link != '#'%>
               	 <a href="<%= banner.link %>">
               	<% end %>
                		<img src="<%= banner.image.url(:original) %>" <%= (banner.link == '#') ? 'class=no-link-banner' : ''%>>
                <% if banner.link != '#'%>
                	</a>
                <% end %>
                </div>
                <div class="clear"></div>
                <div class="content">
                	<ul class="breadcrumbs">
                		<%= render_breadcrumbs :tag => :li, :separator => '<li class="devider">&nbsp;>>&nbsp;</li>' %>
                	</ul>
                    <div class="clear"></div>
                    
<%= yield %>

                    <div class="clear"></div>
                </div>
            </div>
            <%= render :partial => 'layouts/right_panel'%>
            <div class="clear"></div>
        </div>
    </div>
    <div class="footer">
        <div class="container-center">
            <ul class="bottom-menu">
                <li><a href="/">Главная</a></li>
                <li><a href="/archive">Архив</a></li>
                <li><a href="/adverts">Объявления</a></li>
                <li><a href="/advertisers">Рекламодателям</a></li>
                <li><a href="/partners">Партнеры</a></li>
                <li><a href="/contacts">Контакты</a></li>
            </ul>
        </div>
    </div>
    <div id="overlay"></div>
    <div id="pop-up">
    	<% if @forms_errors == 0 %>
    		<%= render :partial => 'forms/success_form'%>
    		<script type="text/javascript">
        		$(document).ready(function(){
        				$("#pop-up").css('min-height', '40px');
        				open_form();
        		})
        		
        	</script>
    	<% else %>
			<%= render :partial => 'forms/ad_form'%>
		<% end %>
    </div>
</body>
</html>

app/views/layouts/empty.html.erb
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <link rel="icon" type="image/png" href="favicon.png">
    <title></title>
</head>
<body>
<%= yield %>
</body>
</html>

app/views/layouts/view.html.erb
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <link rel="icon" type="image/png" href="favicon.png">
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <title><%= @meta_title.reverse.join("&nbsp;&mdash;&nbsp;").html_safe%></title>
    <%= csrf_meta_tag %>
</head>
<body style="overflow:hidden; height:100%;margin: 0">
<%= yield %>
</body>
</html>